---
# 核心任务
- name: Odoo
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml
  
  roles:
    - {role: role_common, tags: "role_common"}
    - {role: role_cloud, tags: "role_cloud"}
    - {role: role_nginx, tags: "role_nginx"}
    - {role: odoo, tags: "odoo"}
    - {role: role_wkhtmltopdf, tags: "role_wkhtmltopdf"}
    - {role: role_preend, tags: "role_preend"}
    - {role: role_end, tags: "role_end"}