- src: https://github.com/websoft9dev/role_common
  version: master
  
- src: https://github.com/websoft9dev/role_cloud
  version: master

- src: https://github.com/websoft9dev/role_nginx
  version: master

- src: https://github.com/websoft9dev/role_postgresql
  version: master

- src: https://github.com/websoft9dev/role_wkhtmltopdf
  version: master

- src: https://github.com/websoft9dev/role_init_password
  version: master

- src: https://github.com/websoft9dev/role_preend
  version: master

- src: https://github.com/websoft9dev/role_end
  version: master